import './globals.css'

export const metadata = {
    title: 'Gift-card-next',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
